[package]
name = "quicksort"
description = "Naive, inefficient quicksort implementation for demonstrating property-based testing"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.9"
